# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('user', 'id')]),
        ),
    ]
