# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='dmodel_type',
            field=models.CharField(choices=[('scube', 'scube'), ('mmaps', 'mmaps')], default='scube', max_length=10),
        ),
        migrations.AlterField(
            model_name='galaxymodel',
            name='gmodel_type',
            field=models.CharField(choices=[('gmodel1', 'gmodel1')], default='gmodel1', max_length=13),
        ),
    ]
