# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0002_auto_20171003_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('A/Prof', 'A/Prof')], default='', max_length=10),
        ),
    ]
