# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0002_auto_20171117_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='dmodel_type',
            field=models.CharField(choices=[('scube', 'Spectral cube'), ('mmaps', 'Moment map')], default='scube', max_length=10),
        ),
        migrations.AlterField(
            model_name='lsf',
            name='lsf_type',
            field=models.CharField(choices=[('gaussian', 'Gaussian'), ('moffat', 'Moffat'), ('lorentzian', 'Lorentzian')], default='gaussian', max_length=10),
        ),
        migrations.AlterField(
            model_name='psf',
            name='psf_type',
            field=models.CharField(choices=[('gaussian', 'Gaussian'), ('moffat', 'Moffat'), ('lorentzian', 'Lorentzian')], default='gaussian', max_length=10),
        ),
    ]
