# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0002_auto_20181115_1019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultfile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='resultfile',
            name='result',
        ),
        migrations.AlterField(
            model_name='modeimage',
            name='image_file',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.DeleteModel(
            name='ResultFile',
        ),
    ]
