# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0003_auto_20171020_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxymodel',
            name='gmodel_type',
            field=models.CharField(choices=[('thindisk_omp', 'thindisk_omp'), ('thindisk_cuda', 'thindisk_cuda')], default='thindisk_omp', max_length=13),
        ),
    ]
