# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0003_auto_20171003_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('scube_omp', 'scube_omp'), ('scube_cuda', 'scube_cuda'), ('mmnt_omp', 'mmnt_omp'), ('mmnt_cuda', 'mmnt_cuda')], default='scube_omp', max_length=10)),
                ('size_x', models.PositiveIntegerField(default=1)),
                ('size_y', models.PositiveIntegerField(default=1)),
                ('size_z', models.PositiveIntegerField(blank=True)),
                ('step_x', models.PositiveIntegerField(default=1)),
                ('step_y', models.PositiveIntegerField(default=1)),
                ('step_z', models.PositiveIntegerField(blank=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_data_model', to='gbkfit_web.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Fitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mpfit', 'mpfit'), ('multinest', 'multinest')], default='mpfit', max_length=10)),
                ('ftol', models.PositiveIntegerField(blank=True, default=1)),
                ('xtol', models.PositiveIntegerField(blank=True, default=1)),
                ('gtol', models.PositiveIntegerField(blank=True, default=1)),
                ('epsfcn', models.PositiveIntegerField(blank=True, default=1)),
                ('stepfactor', models.PositiveIntegerField(blank=True, default=1)),
                ('covtol', models.PositiveIntegerField(blank=True, default=1)),
                ('maxfev', models.PositiveIntegerField(blank=True, default=1)),
                ('nprint', models.PositiveIntegerField(blank=True, default=1)),
                ('douserscale', models.PositiveIntegerField(blank=True, default=1)),
                ('nofinitecheck', models.PositiveIntegerField(blank=True, default=1)),
                ('efr', models.PositiveIntegerField(blank=True, default=1)),
                ('tol', models.PositiveIntegerField(blank=True, default=1)),
                ('ztol', models.PositiveIntegerField(blank=True, default=1)),
                ('logzero', models.PositiveIntegerField(blank=True, default=1)),
                ('_is', models.PositiveIntegerField(blank=True, default=1)),
                ('mmodal', models.PositiveIntegerField(blank=True, default=1)),
                ('ceff', models.PositiveIntegerField(blank=True, default=1)),
                ('nlive', models.PositiveIntegerField(blank=True, default=1)),
                ('maxiter', models.PositiveIntegerField(blank=True, default=1)),
                ('seed', models.PositiveIntegerField(blank=True, default=1)),
                ('outfile', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fitter', to='gbkfit_web.Job')),
            ],
        ),
        migrations.CreateModel(
            name='GalaxyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('thindisk_omp', 'thindisk_omp'), ('thindisk_cuda', 'thindisk_cuda')], default='thindisk_omp', max_length=10)),
                ('fprofile_type', models.CharField(choices=[('exponential', 'exponential'), ('flat', 'flat'), (('boissier',), ('boissier',)), ('arctan', 'arctan'), ('epinat', 'epinat'), ('rings', 'rings')], default='exponential', max_length=10)),
                ('vprofile_type', models.CharField(choices=[('exponential', 'exponential'), ('flat', 'flat'), (('boissier',), ('boissier',)), ('arctan', 'arctan'), ('epinat', 'epinat'), ('rings', 'rings')], default='exponential', max_length=10)),
                ('nrings', models.PositiveIntegerField(blank=True, default=1)),
                ('rsize', models.PositiveIntegerField(blank=True, default=1)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_gmodel', to='gbkfit_web.Job')),
            ],
        ),
        migrations.CreateModel(
            name='LSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('gauss', 'gauss'), ('moffat', 'moffat'), ('lorentz', 'lorentz')], default='gauss', max_length=10)),
                ('fwhm', models.FloatField(default=1.0)),
                ('beta', models.FloatField(default=1.0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_lsf', to='gbkfit_web.Job')),
            ],
        ),
        migrations.CreateModel(
            name='PSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('gauss', 'gauss'), ('moffat', 'moffat'), ('lorentz', 'lorentz')], default='gauss', max_length=10)),
                ('fwhm_x', models.FloatField(default=1.0)),
                ('fwhm_y', models.FloatField(default=1.0)),
                ('pa', models.IntegerField(default=1)),
                ('beta', models.FloatField(default=1.0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_psf', to='gbkfit_web.Job')),
            ],
        ),
    ]
