# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 22:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0004_auto_20171023_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='logzero',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='multinest_maxiter',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='outfile',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='ztol',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='lsf',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='lsf',
            name='fwhm',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='psf',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='psf',
            name='fwhm_x',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='psf',
            name='fwhm_y',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
