# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0004_datamodel_fitter_galaxymodel_lsf_psf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxymodel',
            name='fprofile_type',
            field=models.CharField(choices=[('exponential', 'exponential'), ('flat', 'flat'), (('boissier',), ('boissier',)), ('arctan', 'arctan'), ('epinat', 'epinat'), ('rings', 'rings')], default='exponential', max_length=11),
        ),
        migrations.AlterField(
            model_name='galaxymodel',
            name='type',
            field=models.CharField(choices=[('thindisk_omp', 'thindisk_omp'), ('thindisk_cuda', 'thindisk_cuda')], default='thindisk_omp', max_length=12),
        ),
        migrations.AlterField(
            model_name='galaxymodel',
            name='vprofile_type',
            field=models.CharField(choices=[('exponential', 'exponential'), ('flat', 'flat'), (('boissier',), ('boissier',)), ('arctan', 'arctan'), ('epinat', 'epinat'), ('rings', 'rings')], default='exponential', max_length=11),
        ),
    ]
