# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gbkfit_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0005_auto_20171121_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=gbkfit_web.models.user_job_result_files_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='resultfile',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='resultfile',
            name='filetype',
        ),
        migrations.AddField(
            model_name='mode',
            name='mode_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='tar_file',
            field=models.FileField(null=True, upload_to=gbkfit_web.models.user_job_result_files_directory_path),
        ),
        migrations.AlterField(
            model_name='resultfile',
            name='result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_file_mode', to='gbkfit_web.Result'),
        ),
        migrations.AddField(
            model_name='modeimage',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_mode_image', to='gbkfit_web.Mode'),
        ),
    ]
