# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0005_auto_20171024_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='ceff',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='douserscale',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='mmodal',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='multinest_is',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nofinitecheck',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nprint',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='outfile',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=1),
        ),
    ]
