# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0006_auto_20171024_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='ceff',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='douserscale',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='mmodal',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='multinest_is',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nofinitecheck',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nprint',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='outfile',
            field=models.BooleanField(default=1),
        ),
    ]
