# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0006_auto_20171121_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='dmodel_type',
            field=models.CharField(choices=[('scube', 'Spectral cube'), ('mmaps', 'Moment map')], default='mmaps', max_length=10),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='scale_x',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='scale_y',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='scale_z',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='step_x',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='step_y',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='step_z',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='a_fixed',
            field=models.NullBooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='a_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='b_fixed',
            field=models.NullBooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='b_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='i0_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='incl_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pa_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='r0_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='rt_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vsig_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vsys_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vt_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='xo_wrap',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='yo_wrap',
            field=models.NullBooleanField(default=0),
        ),
    ]
