# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 05:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0007_auto_20171123_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='covtol',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='efr',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='epsfcn',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='ftol',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='gtol',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='maxfev',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='mpfit_maxiter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nlive',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='seed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='stepfactor',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='tol',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='xtol',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
