# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0008_auto_20171123_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset2_type',
            field=models.CharField(blank=True, choices=[('flxmap', 'Flux map'), ('velmap', 'Velocity map'), ('sigmap', 'Velocity dispersion map'), ('flxcube', 'Spectral cubes')], default='sigmap', max_length=10),
        ),
    ]
