# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 01:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0008_auto_20171025_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='a_fixed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_max',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_min',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_relstep',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_side',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_step',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_value',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='a_wrap',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_fixed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_max',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_min',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_relstep',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_side',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_step',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_value',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='b_wrap',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
