# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0009_auto_20171026_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='multinest_is',
            field=models.BooleanField(default=True),
        ),
    ]
