# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0010_remove_mode_mode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='mode_number',
            field=models.IntegerField(default=0),
        ),
    ]
