# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0010_auto_20171026_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='douserscale',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nofinitecheck',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nprint',
            field=models.BooleanField(default=1),
        ),
    ]
