# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0012_auto_20171026_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='a_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='b_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='rt_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vt_fixed',
            field=models.NullBooleanField(default=0),
        ),
    ]
