# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 04:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0012_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='covtol',
            field=models.FloatField(default=1e-14, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='douserscale',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='efr',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='epsfcn',
            field=models.FloatField(default=-1e+90, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='ftol',
            field=models.FloatField(default=1e-10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='gtol',
            field=models.FloatField(default=1e-10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='logzero',
            field=models.FloatField(blank=True, default=-1e+90, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='maxfev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='mpfit_maxiter',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nlive',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nofinitecheck',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='nprint',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='stepfactor',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='tol',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='xtol',
            field=models.FloatField(default=1e-10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='ztol',
            field=models.FloatField(blank=True, default=-1e+90, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
