# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0013_auto_20171026_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='i0_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='incl_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pa_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='r0_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vsig_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vsys_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='xo_fixed',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='yo_fixed',
            field=models.NullBooleanField(default=0),
        ),
    ]
