# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 23:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0013_auto_20171128_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='a_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='a_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='b_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='b_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='i0_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='i0_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='incl_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='incl_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pa_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pa_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='r0_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='r0_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='rt_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='rt_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vsys_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vsys_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vt_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='vt_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='xo_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='xo_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='yo_relstep',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='yo_step',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='datamodel',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='fitter',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='galaxymodel',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='jobresults',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='lsf',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='mode',
            unique_together=set([('result', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='modeimage',
            unique_together=set([('mode', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='modeparameter',
            unique_together=set([('mode', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='parameterset',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='psf',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('job', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='resultfile',
            unique_together=set([('result', 'id')]),
        ),
    ]
