# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0014_auto_20171026_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxymodel',
            name='gmodel_type',
            field=models.CharField(choices=[('gmodel1_omp', 'gmodel1_omp'), ('gmodel1_cuda', 'gmodel1_cuda')], default='gmodel1_omp', max_length=13),
        ),
    ]
