# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 00:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0015_auto_20171130_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitter',
            name='efr',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
        migrations.AlterField(
            model_name='fitter',
            name='tol',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
        migrations.AlterField(
            model_name='lsf',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
        migrations.AlterField(
            model_name='lsf',
            name='fwhm',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
        migrations.AlterField(
            model_name='psf',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
        migrations.AlterField(
            model_name='psf',
            name='fwhm_x',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
        migrations.AlterField(
            model_name='psf',
            name='fwhm_y',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-90)]),
        ),
    ]
