# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0016_auto_20171102_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxymodel',
            name='vel_profile',
            field=models.CharField(choices=[('arctan', 'arctan'), ('boissier', 'boissier'), ('lramp', 'lramp'), ('epinat', 'epinat')], default='arctan', max_length=11),
        ),
    ]
