# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0017_auto_20171130_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeimage',
            name='image_type',
            field=models.CharField(default='velmap', max_length=10),
        ),
    ]
