# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0018_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chisqr', models.FloatField()),
                ('rchisqr', models.FloatField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('error', models.FloatField()),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_mode_parameters', to='gbkfit_web.Mode')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dof', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_result', to='gbkfit_web.Job')),
            ],
        ),
        migrations.AddField(
            model_name='mode',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_mode', to='gbkfit_web.Result'),
        ),
    ]
