# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0020_resultfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_job_results', to='gbkfit_web.Job')),
            ],
        ),
    ]
