# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import gbkfit_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('gbkfit_web', '0021_jobresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeParameters',
            new_name='ModeParameter',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='fitter',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='galaxymodel',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='jobresults',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='lsf',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='psf',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='resultfile',
            name='image',
            field=models.FileField(null=True, upload_to=gbkfit_web.models.user_job_data_image_directory_path),
        ),
    ]
